import { useState, useRef, useEffect } from "react";
import { navigate } from "../App";
import { getFeedItem, feedItems, type FeedItem } from "../data/mockData";

// Simple markdown-ish renderer for chat messages
const renderChatMarkdown = (text: string) => {
  const lines = text.split("\n");
  const elements: JSX.Element[] = [];
  let key = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith("### ")) {
      elements.push(<h3 key={key++}>{line.slice(4)}</h3>);
    } else if (line.startsWith("## ")) {
      elements.push(<h3 key={key++}>{line.slice(3)}</h3>);
    } else if (line.startsWith("> *")) {
      const content = line.slice(3, line.endsWith("*") ? -1 : undefined);
      elements.push(<blockquote key={key++}>{content}</blockquote>);
    } else if (line.startsWith("> ")) {
      elements.push(<blockquote key={key++}>{line.slice(2)}</blockquote>);
    } else if (line.startsWith("---")) {
      elements.push(<hr key={key++} />);
    } else if (line.startsWith("- **")) {
      const boldEnd = line.indexOf("**", 4);
      if (boldEnd > 0) {
        const boldText = line.slice(4, boldEnd);
        const rest = line.slice(boldEnd + 2);
        elements.push(
          <li key={key++}>
            <strong>{boldText}</strong>
            {rest}
          </li>,
        );
      } else {
        elements.push(<li key={key++}>{line.slice(2)}</li>);
      }
    } else if (line.startsWith("- ")) {
      elements.push(<li key={key++}>{line.slice(2)}</li>);
    } else if (line.trim() === "") {
      // skip
    } else {
      // Handle inline bold
      const parts = line.split(/(\*\*[^*]+\*\*)/g);
      const rendered = parts.map((part, j) => {
        if (part.startsWith("**") && part.endsWith("**")) {
          return <strong key={j}>{part.slice(2, -2)}</strong>;
        }
        return part;
      });
      elements.push(<p key={key++}>{rendered}</p>);
    }
  }

  return elements;
};

type ChatMessage = {
  id: string;
  role: "user" | "assistant";
  text: string;
};

const buildInitialSummary = (item: FeedItem): string => {
  let summary = `**Summary of deliberation: ${item.headline}**\n\n`;
  summary += `${item.description}\n\n`;

  if (item.deliberativeQuestion) {
    summary += `The central question before the committee: *${item.deliberativeQuestion}*\n\n`;
  }

  if (item.keyQuotes && item.keyQuotes.length > 0) {
    summary += `### Key statements\n\n`;
    for (const kq of item.keyQuotes) {
      summary += `**${kq.speaker}**${kq.role ? ` (${kq.role})` : ""}:\n`;
      summary += `> *"${kq.quote}"*\n\n`;
    }
  }

  if (item.negationGameUrl) {
    summary += `The structured deliberation board below maps out the arguments, counter-arguments, and evidence on this topic. You can explore the full argument map or ask me questions about specific points.`;
  } else {
    summary += `This topic does not yet have a structured deliberation board. You can ask me questions about the discussion, key arguments, and related transcript excerpts.`;
  }

  return summary;
};

const TopicDetailPage = ({ topicId }: { topicId: string }) => {
  const item = getFeedItem(topicId);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Scroll to top and build initial summary when topic loads
  useEffect(() => {
    window.scrollTo(0, 0);
    document.querySelector('.topic-main')?.scrollTo(0, 0);
    if (item) {
      setChatMessages([
        {
          id: "summary",
          role: "assistant",
          text: buildInitialSummary(item),
        },
      ]);
    }
  }, [topicId]);

  useEffect(() => {
    // Scroll only the chat container, not the whole page
    const chatContainer = messagesEndRef.current?.closest('.chat-messages');
    if (chatContainer) {
      chatContainer.scrollTop = chatContainer.scrollHeight;
    }
  }, [chatMessages]);

  if (!item) {
    return (
      <div style={{ padding: "2rem", textAlign: "center" }}>
        <p>Topic not found.</p>
        <a href="#/home" onClick={(e) => { e.preventDefault(); navigate("/home"); }}>
          ← Back to feed
        </a>
      </div>
    );
  }

  const otherQuestions = feedItems.filter(
    (fi) =>
      fi.id !== item.id &&
      fi.committee.id === item.committee.id &&
      fi.deliberativeQuestion,
  );

  const handleChatSend = () => {
    const text = chatInput.trim();
    if (!text) return;
    setChatInput("");
    setChatMessages((prev) => [
      ...prev,
      { id: `u-${Date.now()}`, role: "user", text },
      {
        id: `a-${Date.now()}`,
        role: "assistant",
        text: `Thank you for your question about "${text}". In the demo, this response would be generated by AI using the transcript data and deliberation records for this topic. Louis will connect the real AI backend here.`,
      },
    ]);
  };

  return (
    <div style={{ height: "100vh", overflow: "hidden", background: "var(--msga-bg)" }}>
      {/* Header */}
      <header className="msga-header">
        <a
          href="#/"
          className="msga-header-logo"
          onClick={(e) => {
            e.preventDefault();
            navigate("/");
          }}
        >
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
            <rect width="24" height="24" rx="4" fill="white" fillOpacity="0.2" />
            <path d="M6 8h12M6 12h12M6 16h8" stroke="white" strokeWidth="1.5" strokeLinecap="round" />
          </svg>
          MISSISSAUGA
        </a>
        <div className="msga-header-subtitle" style={{ color: "white", fontSize: "0.85rem", fontWeight: 600, letterSpacing: "0.3px" }}>
          Civic Deliberative Memory
        </div>
      </header>

      {/* Nav */}
      <nav className="msga-nav">
        <a
          href="#/home"
          className="msga-nav-item"
          onClick={(e) => {
            e.preventDefault();
            navigate("/home");
          }}
        >
          ← Home
        </a>
        <div className="msga-nav-item active" style={{ fontSize: "0.75rem" }}>
          {item.committee.name}
        </div>
      </nav>

      {/* Main layout */}
      <div className="topic-detail-layout">
        {/* Left: Topic content + Negation Game */}
        <div className="topic-main">
          <div className="topic-meta">
            <span className="topic-committee-tag">{item.committee.name}</span>
            <span className="topic-date">{item.date}</span>
          </div>

          <h1 className="topic-title">{item.headline}</h1>
          <p className="topic-description">{item.description}</p>

          {/* Key quotes */}
          {item.keyQuotes && item.keyQuotes.length > 0 && (
            <>
              <div className="topic-section-header">Key statements</div>
              {item.keyQuotes.map((kq, idx) => (
                <div key={idx} className="feed-item-quote" style={{ marginBottom: "0.75rem" }}>
                  <div className="feed-item-quote-speaker">
                    {kq.speaker}
                    {kq.role ? `, ${kq.role}` : ""}
                  </div>
                  <div className="feed-item-quote-text">"{kq.quote}"</div>
                  {item.hasAudio && (
                    <button className="feed-item-audio-btn" style={{ marginTop: "0.35rem" }}>
                      <svg width="12" height="12" viewBox="0 0 14 14" fill="none">
                        <circle cx="7" cy="7" r="6.5" stroke="currentColor" />
                        <path d="M5.5 4.5L9.5 7L5.5 9.5V4.5Z" fill="currentColor" />
                      </svg>
                      Listen
                    </button>
                  )}
                </div>
              ))}
            </>
          )}

          {/* Negation Game embed */}
          {item.negationGameUrl ? (
            <>
              <div className="topic-section-header">Deliberation Map</div>
              <div className="topic-negation-frame">
                <iframe
                  src={item.negationGameUrl}
                  title="Negation Game — Deliberation Map"
                  allow="clipboard-write"
                />
              </div>
            </>
          ) : (
            <>
              <div className="topic-section-header">Discussion Summary</div>
              <div
                className="msga-callout"
                style={{ fontSize: "0.85rem", lineHeight: 1.6 }}
              >
                A structured deliberation map has not yet been generated for this
                topic. The key arguments and evidence from council transcripts are
                summarized in the chat panel. As more transcript data becomes
                available, a full argument map will be generated automatically.
              </div>
            </>
          )}

          {/* Other questions from same committee */}
          {otherQuestions.length > 0 && (
            <>
              <div className="topic-section-header">
                Other questions — {item.committee.name}
              </div>
              <ul className="topic-other-questions">
                {otherQuestions.map((oq) => (
                  <li key={oq.id}>
                    <a
                      href={`#/topic/${oq.id}`}
                      onClick={(e) => {
                        e.preventDefault();
                        navigate(`/topic/${oq.id}`);
                      }}
                    >
                      {oq.deliberativeQuestion || oq.headline}
                    </a>
                  </li>
                ))}
              </ul>
            </>
          )}
        </div>

        {/* Right: Chat panel */}
        <div className="topic-chat-panel">
          <div
            style={{
              padding: "0.75rem 1rem",
              borderBottom: "1px solid var(--msga-border)",
              background: "white",
              fontSize: "0.8rem",
              fontWeight: 700,
              fontFamily: "var(--msga-font-heading)",
              color: "var(--msga-text)",
            }}
          >
            Ask about this topic
          </div>

          <div className="chat-messages">
            {chatMessages.map((msg) => (
              <div key={msg.id} className={`chat-msg ${msg.role}`}>
                {msg.role === "assistant"
                  ? renderChatMarkdown(msg.text)
                  : msg.text}
              </div>
            ))}
            <div ref={messagesEndRef} />
          </div>

          <div className="chat-input-area">
            <input
              className="chat-input"
              type="text"
              placeholder="Ask a question about this topic…"
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  handleChatSend();
                }
              }}
            />
            <button className="chat-send-btn" onClick={handleChatSend}>
              Send
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TopicDetailPage;
